### PR TITLE
Fix release date for 0.5.2

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
zest.releaser full-release will automatically update the release date for you.

**Comment by jkaldon** [comment]
@graingert Think you could walk me through doing a release?  I took over on this project a few months ago and have never worked with zest.releaser.

**Comment by graingert** [comment]
@jkaldon here's a doc for https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/README.rst#releasing

**Comment by graingert** [comment]
@jkaldon any chance of a release?

**Comment by jkaldon** [comment]
Yup - just released the currently pending changes.  Thanks for the link to the README.

**Comment by graingert** [comment]
@jkaldon the fullrelease command should have created some commits and tags for you to push. Did you forget to push them?

If you answer default to all prompts it should do it for you.

**Pull request merged**
